spring:
  datasource:
    username: postgres
    password: qWqNtEyfeZfPYusWDSQNhdAJNostTfcL
    url: jdbc:postgresql://roundhouse.proxy.rlwy.net:57940/railway
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  graphql:
    cors:
      allowed-origins: https://master--cepheus-service.netlify.app

web:
  cepheusservice:
    secret_key: "7a2357643121767939494e7a4036794c7276623c657936246e442b475a702068"